name: ci

on: push

jobs:
  sounds-builder:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        # 1.8 not supported for Burger's sound 'topping' (command)
        version: ["1.16.5", "1.16.4", "1.16.3", "1.16.2", "1.16.1", "1.16", "1.15.2", "1.15.1", "1.15", "1.14.4", "1.14.3", "1.14.2", "1.14.1", "1.14", "1.13.2", "1.13.1", "1.13", "1.12.2", "1.12.1", "1.12", "1.11.2", "1.11.1", "1.11", "1.10.2", "1.10.1", "1.10", "1.9.4", "1.9.3", "1.9.2", "1.9.1", "1.9"]
    env:
      working-directory: ./sounds/burger
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'
      - name: Install project dependencies
        run: python3 setup.py install
        working-directory: ${{ env.working-directory }}
      - name: Build sounds json file
        run: python3 munch.py --download ${{ matrix.version }} --toppings sounds | jq .[0].sounds > sounds.json
        working-directory: ${{ env.working-directory }}
      - name: Send data to publish job
        uses: actions/upload-artifact@v2
        with:
          name: sounds-${{ matrix.version }}
          path: ${{ env.working-directory }}/sounds.json
  ids-builder:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 14.x
      - name: Install project dependencies
        run: npm install --ignore-scripts
      - name: Build json data
        run: node index.js
      - name: Send data to publish job
        uses: actions/upload-artifact@v2
        with:
          name: ids
          path: data.json
  publisher:
    needs: [sounds-builder, ids-builder]
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/download-artifact@v2
      - name: Display structure of downloaded files
        run: ls -lR